spring.application.name=backend_pfe
#spring.datasource.url=jdbc:h2:mem:hospital_db
#spring.h2.console.enabled=true
server.port=9090


spring.datasource.url=jdbc:postgresql://localhost:5433/pfeapp
#spring.datasource.url=jdbc:postgresql://localhost:5432/pfeapp
spring.datasource.username=ilcs
spring.datasource.password=ilcs1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAILUSERNAME}
spring.mail.password=${EMAILPASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.security.oauth2.client.registration.google.client-id=${OAUTH2}
spring.security.oauth2.client.registration.google.client-secret=${SECRETOAUTH2}
